// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: aptos/util/timestamp/timestamp.proto

package timestamppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos         int32 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_aptos_util_timestamp_timestamp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_util_timestamp_timestamp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_aptos_util_timestamp_timestamp_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_aptos_util_timestamp_timestamp_proto protoreflect.FileDescriptor

const file_aptos_util_timestamp_timestamp_proto_rawDesc = "" +
	"\n" +
	"$aptos/util/timestamp/timestamp.proto\x12\x14aptos.util.timestamp\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanosBHZFgithub.com/xiaobaiskill/aptos-grpc-go/aptos/util/timestamp;timestamppbb\x06proto3"

var (
	file_aptos_util_timestamp_timestamp_proto_rawDescOnce sync.Once
	file_aptos_util_timestamp_timestamp_proto_rawDescData []byte
)

func file_aptos_util_timestamp_timestamp_proto_rawDescGZIP() []byte {
	file_aptos_util_timestamp_timestamp_proto_rawDescOnce.Do(func() {
		file_aptos_util_timestamp_timestamp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aptos_util_timestamp_timestamp_proto_rawDesc), len(file_aptos_util_timestamp_timestamp_proto_rawDesc)))
	})
	return file_aptos_util_timestamp_timestamp_proto_rawDescData
}

var file_aptos_util_timestamp_timestamp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aptos_util_timestamp_timestamp_proto_goTypes = []any{
	(*Timestamp)(nil), // 0: aptos.util.timestamp.Timestamp
}
var file_aptos_util_timestamp_timestamp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aptos_util_timestamp_timestamp_proto_init() }
func file_aptos_util_timestamp_timestamp_proto_init() {
	if File_aptos_util_timestamp_timestamp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aptos_util_timestamp_timestamp_proto_rawDesc), len(file_aptos_util_timestamp_timestamp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aptos_util_timestamp_timestamp_proto_goTypes,
		DependencyIndexes: file_aptos_util_timestamp_timestamp_proto_depIdxs,
		MessageInfos:      file_aptos_util_timestamp_timestamp_proto_msgTypes,
	}.Build()
	File_aptos_util_timestamp_timestamp_proto = out.File
	file_aptos_util_timestamp_timestamp_proto_goTypes = nil
	file_aptos_util_timestamp_timestamp_proto_depIdxs = nil
}
