// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: aptos/internal/fullnode/v1/fullnode_data.proto

package fullnodev1

import (
	v11 "github.com/xiaobaiskill/aptos-grpc-go/aptos/indexer/v1"
	v1 "github.com/xiaobaiskill/aptos-grpc-go/aptos/transaction/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamStatus_StatusType int32

const (
	StreamStatus_STATUS_TYPE_UNSPECIFIED StreamStatus_StatusType = 0
	// Signal for the start of the stream.
	StreamStatus_STATUS_TYPE_INIT StreamStatus_StatusType = 1
	// Signal for the end of the batch.
	StreamStatus_STATUS_TYPE_BATCH_END StreamStatus_StatusType = 2
)

// Enum value maps for StreamStatus_StatusType.
var (
	StreamStatus_StatusType_name = map[int32]string{
		0: "STATUS_TYPE_UNSPECIFIED",
		1: "STATUS_TYPE_INIT",
		2: "STATUS_TYPE_BATCH_END",
	}
	StreamStatus_StatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED": 0,
		"STATUS_TYPE_INIT":        1,
		"STATUS_TYPE_BATCH_END":   2,
	}
)

func (x StreamStatus_StatusType) Enum() *StreamStatus_StatusType {
	p := new(StreamStatus_StatusType)
	*p = x
	return p
}

func (x StreamStatus_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamStatus_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_enumTypes[0].Descriptor()
}

func (StreamStatus_StatusType) Type() protoreflect.EnumType {
	return &file_aptos_internal_fullnode_v1_fullnode_data_proto_enumTypes[0]
}

func (x StreamStatus_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamStatus_StatusType.Descriptor instead.
func (StreamStatus_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescGZIP(), []int{1, 0}
}

type TransactionsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*v1.Transaction      `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsOutput) Reset() {
	*x = TransactionsOutput{}
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsOutput) ProtoMessage() {}

func (x *TransactionsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsOutput.ProtoReflect.Descriptor instead.
func (*TransactionsOutput) Descriptor() ([]byte, []int) {
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionsOutput) GetTransactions() []*v1.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type StreamStatus struct {
	state protoimpl.MessageState  `protogen:"open.v1"`
	Type  StreamStatus_StatusType `protobuf:"varint,1,opt,name=type,proto3,enum=aptos.internal.fullnode.v1.StreamStatus_StatusType" json:"type,omitempty"`
	// Required. Start version of current batch/stream, inclusive.
	StartVersion uint64 `protobuf:"varint,2,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	// End version of current *batch*, inclusive.
	EndVersion    *uint64 `protobuf:"varint,3,opt,name=end_version,json=endVersion,proto3,oneof" json:"end_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatus) Reset() {
	*x = StreamStatus{}
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatus) ProtoMessage() {}

func (x *StreamStatus) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatus.ProtoReflect.Descriptor instead.
func (*StreamStatus) Descriptor() ([]byte, []int) {
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescGZIP(), []int{1}
}

func (x *StreamStatus) GetType() StreamStatus_StatusType {
	if x != nil {
		return x.Type
	}
	return StreamStatus_STATUS_TYPE_UNSPECIFIED
}

func (x *StreamStatus) GetStartVersion() uint64 {
	if x != nil {
		return x.StartVersion
	}
	return 0
}

func (x *StreamStatus) GetEndVersion() uint64 {
	if x != nil && x.EndVersion != nil {
		return *x.EndVersion
	}
	return 0
}

type GetTransactionsFromNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required; start version of current stream.
	// If not set will panic somewhere
	StartingVersion *uint64 `protobuf:"varint,1,opt,name=starting_version,json=startingVersion,proto3,oneof" json:"starting_version,omitempty"`
	// Optional; number of transactions to return in current stream.
	// If not set, response streams infinitely.
	TransactionsCount *uint64 `protobuf:"varint,2,opt,name=transactions_count,json=transactionsCount,proto3,oneof" json:"transactions_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTransactionsFromNodeRequest) Reset() {
	*x = GetTransactionsFromNodeRequest{}
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsFromNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsFromNodeRequest) ProtoMessage() {}

func (x *GetTransactionsFromNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsFromNodeRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsFromNodeRequest) Descriptor() ([]byte, []int) {
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionsFromNodeRequest) GetStartingVersion() uint64 {
	if x != nil && x.StartingVersion != nil {
		return *x.StartingVersion
	}
	return 0
}

func (x *GetTransactionsFromNodeRequest) GetTransactionsCount() uint64 {
	if x != nil && x.TransactionsCount != nil {
		return *x.TransactionsCount
	}
	return 0
}

type TransactionsFromNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*TransactionsFromNodeResponse_Status
	//	*TransactionsFromNodeResponse_Data
	Response isTransactionsFromNodeResponse_Response `protobuf_oneof:"response"`
	// Making sure that all the responses include a chain id
	ChainId       uint32 `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsFromNodeResponse) Reset() {
	*x = TransactionsFromNodeResponse{}
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsFromNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsFromNodeResponse) ProtoMessage() {}

func (x *TransactionsFromNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsFromNodeResponse.ProtoReflect.Descriptor instead.
func (*TransactionsFromNodeResponse) Descriptor() ([]byte, []int) {
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionsFromNodeResponse) GetResponse() isTransactionsFromNodeResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TransactionsFromNodeResponse) GetStatus() *StreamStatus {
	if x != nil {
		if x, ok := x.Response.(*TransactionsFromNodeResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *TransactionsFromNodeResponse) GetData() *TransactionsOutput {
	if x != nil {
		if x, ok := x.Response.(*TransactionsFromNodeResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TransactionsFromNodeResponse) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type isTransactionsFromNodeResponse_Response interface {
	isTransactionsFromNodeResponse_Response()
}

type TransactionsFromNodeResponse_Status struct {
	Status *StreamStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type TransactionsFromNodeResponse_Data struct {
	Data *TransactionsOutput `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*TransactionsFromNodeResponse_Status) isTransactionsFromNodeResponse_Response() {}

func (*TransactionsFromNodeResponse_Data) isTransactionsFromNodeResponse_Response() {}

type PingFullnodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingFullnodeRequest) Reset() {
	*x = PingFullnodeRequest{}
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFullnodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFullnodeRequest) ProtoMessage() {}

func (x *PingFullnodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFullnodeRequest.ProtoReflect.Descriptor instead.
func (*PingFullnodeRequest) Descriptor() ([]byte, []int) {
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescGZIP(), []int{4}
}

type PingFullnodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *v11.FullnodeInfo      `protobuf:"bytes,1,opt,name=info,proto3,oneof" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingFullnodeResponse) Reset() {
	*x = PingFullnodeResponse{}
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFullnodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFullnodeResponse) ProtoMessage() {}

func (x *PingFullnodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFullnodeResponse.ProtoReflect.Descriptor instead.
func (*PingFullnodeResponse) Descriptor() ([]byte, []int) {
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescGZIP(), []int{5}
}

func (x *PingFullnodeResponse) GetInfo() *v11.FullnodeInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_aptos_internal_fullnode_v1_fullnode_data_proto protoreflect.FileDescriptor

const file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDesc = "" +
	"\n" +
	".aptos/internal/fullnode/v1/fullnode_data.proto\x12\x1aaptos.internal.fullnode.v1\x1a&aptos/transaction/v1/transaction.proto\x1a\x1baptos/indexer/v1/grpc.proto\"[\n" +
	"\x12TransactionsOutput\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.aptos.transaction.v1.TransactionR\ftransactions\"\x92\x02\n" +
	"\fStreamStatus\x12G\n" +
	"\x04type\x18\x01 \x01(\x0e23.aptos.internal.fullnode.v1.StreamStatus.StatusTypeR\x04type\x12#\n" +
	"\rstart_version\x18\x02 \x01(\x04R\fstartVersion\x12(\n" +
	"\vend_version\x18\x03 \x01(\x04B\x020\x01H\x00R\n" +
	"endVersion\x88\x01\x01\"Z\n" +
	"\n" +
	"StatusType\x12\x1b\n" +
	"\x17STATUS_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_TYPE_INIT\x10\x01\x12\x19\n" +
	"\x15STATUS_TYPE_BATCH_END\x10\x02B\x0e\n" +
	"\f_end_version\"\xb8\x01\n" +
	"\x1eGetTransactionsFromNodeRequest\x122\n" +
	"\x10starting_version\x18\x01 \x01(\x04B\x020\x01H\x00R\x0fstartingVersion\x88\x01\x01\x126\n" +
	"\x12transactions_count\x18\x02 \x01(\x04B\x020\x01H\x01R\x11transactionsCount\x88\x01\x01B\x13\n" +
	"\x11_starting_versionB\x15\n" +
	"\x13_transactions_count\"\xcf\x01\n" +
	"\x1cTransactionsFromNodeResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\v2(.aptos.internal.fullnode.v1.StreamStatusH\x00R\x06status\x12D\n" +
	"\x04data\x18\x02 \x01(\v2..aptos.internal.fullnode.v1.TransactionsOutputH\x00R\x04data\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\rR\achainIdB\n" +
	"\n" +
	"\bresponse\"\x15\n" +
	"\x13PingFullnodeRequest\"X\n" +
	"\x14PingFullnodeResponse\x127\n" +
	"\x04info\x18\x01 \x01(\v2\x1e.aptos.indexer.v1.FullnodeInfoH\x00R\x04info\x88\x01\x01B\a\n" +
	"\x05_info2\x8d\x02\n" +
	"\fFullnodeData\x12i\n" +
	"\x04Ping\x12/.aptos.internal.fullnode.v1.PingFullnodeRequest\x1a0.aptos.internal.fullnode.v1.PingFullnodeResponse\x12\x91\x01\n" +
	"\x17GetTransactionsFromNode\x12:.aptos.internal.fullnode.v1.GetTransactionsFromNodeRequest\x1a8.aptos.internal.fullnode.v1.TransactionsFromNodeResponse0\x01BMZKgithub.com/xiaobaiskill/aptos-grpc-go/aptos/internal/fullnode/v1;fullnodev1b\x06proto3"

var (
	file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescOnce sync.Once
	file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescData []byte
)

func file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescGZIP() []byte {
	file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescOnce.Do(func() {
		file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDesc), len(file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDesc)))
	})
	return file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDescData
}

var file_aptos_internal_fullnode_v1_fullnode_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aptos_internal_fullnode_v1_fullnode_data_proto_goTypes = []any{
	(StreamStatus_StatusType)(0),           // 0: aptos.internal.fullnode.v1.StreamStatus.StatusType
	(*TransactionsOutput)(nil),             // 1: aptos.internal.fullnode.v1.TransactionsOutput
	(*StreamStatus)(nil),                   // 2: aptos.internal.fullnode.v1.StreamStatus
	(*GetTransactionsFromNodeRequest)(nil), // 3: aptos.internal.fullnode.v1.GetTransactionsFromNodeRequest
	(*TransactionsFromNodeResponse)(nil),   // 4: aptos.internal.fullnode.v1.TransactionsFromNodeResponse
	(*PingFullnodeRequest)(nil),            // 5: aptos.internal.fullnode.v1.PingFullnodeRequest
	(*PingFullnodeResponse)(nil),           // 6: aptos.internal.fullnode.v1.PingFullnodeResponse
	(*v1.Transaction)(nil),                 // 7: aptos.transaction.v1.Transaction
	(*v11.FullnodeInfo)(nil),               // 8: aptos.indexer.v1.FullnodeInfo
}
var file_aptos_internal_fullnode_v1_fullnode_data_proto_depIdxs = []int32{
	7, // 0: aptos.internal.fullnode.v1.TransactionsOutput.transactions:type_name -> aptos.transaction.v1.Transaction
	0, // 1: aptos.internal.fullnode.v1.StreamStatus.type:type_name -> aptos.internal.fullnode.v1.StreamStatus.StatusType
	2, // 2: aptos.internal.fullnode.v1.TransactionsFromNodeResponse.status:type_name -> aptos.internal.fullnode.v1.StreamStatus
	1, // 3: aptos.internal.fullnode.v1.TransactionsFromNodeResponse.data:type_name -> aptos.internal.fullnode.v1.TransactionsOutput
	8, // 4: aptos.internal.fullnode.v1.PingFullnodeResponse.info:type_name -> aptos.indexer.v1.FullnodeInfo
	5, // 5: aptos.internal.fullnode.v1.FullnodeData.Ping:input_type -> aptos.internal.fullnode.v1.PingFullnodeRequest
	3, // 6: aptos.internal.fullnode.v1.FullnodeData.GetTransactionsFromNode:input_type -> aptos.internal.fullnode.v1.GetTransactionsFromNodeRequest
	6, // 7: aptos.internal.fullnode.v1.FullnodeData.Ping:output_type -> aptos.internal.fullnode.v1.PingFullnodeResponse
	4, // 8: aptos.internal.fullnode.v1.FullnodeData.GetTransactionsFromNode:output_type -> aptos.internal.fullnode.v1.TransactionsFromNodeResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_aptos_internal_fullnode_v1_fullnode_data_proto_init() }
func file_aptos_internal_fullnode_v1_fullnode_data_proto_init() {
	if File_aptos_internal_fullnode_v1_fullnode_data_proto != nil {
		return
	}
	file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[1].OneofWrappers = []any{}
	file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[2].OneofWrappers = []any{}
	file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[3].OneofWrappers = []any{
		(*TransactionsFromNodeResponse_Status)(nil),
		(*TransactionsFromNodeResponse_Data)(nil),
	}
	file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDesc), len(file_aptos_internal_fullnode_v1_fullnode_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aptos_internal_fullnode_v1_fullnode_data_proto_goTypes,
		DependencyIndexes: file_aptos_internal_fullnode_v1_fullnode_data_proto_depIdxs,
		EnumInfos:         file_aptos_internal_fullnode_v1_fullnode_data_proto_enumTypes,
		MessageInfos:      file_aptos_internal_fullnode_v1_fullnode_data_proto_msgTypes,
	}.Build()
	File_aptos_internal_fullnode_v1_fullnode_data_proto = out.File
	file_aptos_internal_fullnode_v1_fullnode_data_proto_goTypes = nil
	file_aptos_internal_fullnode_v1_fullnode_data_proto_depIdxs = nil
}
