// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: aptos/indexer/v1/filter.proto

package indexerv1

import (
	v1 "github.com/xiaobaiskill/aptos-grpc-go/aptos/transaction/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogicalAndFilters struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Filters       []*BooleanTransactionFilter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalAndFilters) Reset() {
	*x = LogicalAndFilters{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalAndFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalAndFilters) ProtoMessage() {}

func (x *LogicalAndFilters) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalAndFilters.ProtoReflect.Descriptor instead.
func (*LogicalAndFilters) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{0}
}

func (x *LogicalAndFilters) GetFilters() []*BooleanTransactionFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type LogicalOrFilters struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Filters       []*BooleanTransactionFilter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalOrFilters) Reset() {
	*x = LogicalOrFilters{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalOrFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalOrFilters) ProtoMessage() {}

func (x *LogicalOrFilters) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalOrFilters.ProtoReflect.Descriptor instead.
func (*LogicalOrFilters) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{1}
}

func (x *LogicalOrFilters) GetFilters() []*BooleanTransactionFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type TransactionRootFilter struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	Success         *bool                           `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	TransactionType *v1.Transaction_TransactionType `protobuf:"varint,2,opt,name=transaction_type,json=transactionType,proto3,enum=aptos.transaction.v1.Transaction_TransactionType,oneof" json:"transaction_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionRootFilter) Reset() {
	*x = TransactionRootFilter{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRootFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRootFilter) ProtoMessage() {}

func (x *TransactionRootFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRootFilter.ProtoReflect.Descriptor instead.
func (*TransactionRootFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRootFilter) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *TransactionRootFilter) GetTransactionType() v1.Transaction_TransactionType {
	if x != nil && x.TransactionType != nil {
		return *x.TransactionType
	}
	return v1.Transaction_TransactionType(0)
}

type EntryFunctionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *string                `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	ModuleName    *string                `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3,oneof" json:"module_name,omitempty"`
	Function      *string                `protobuf:"bytes,3,opt,name=function,proto3,oneof" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryFunctionFilter) Reset() {
	*x = EntryFunctionFilter{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryFunctionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryFunctionFilter) ProtoMessage() {}

func (x *EntryFunctionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryFunctionFilter.ProtoReflect.Descriptor instead.
func (*EntryFunctionFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{3}
}

func (x *EntryFunctionFilter) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *EntryFunctionFilter) GetModuleName() string {
	if x != nil && x.ModuleName != nil {
		return *x.ModuleName
	}
	return ""
}

func (x *EntryFunctionFilter) GetFunction() string {
	if x != nil && x.Function != nil {
		return *x.Function
	}
	return ""
}

type UserTransactionPayloadFilter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EntryFunctionFilter *EntryFunctionFilter   `protobuf:"bytes,1,opt,name=entry_function_filter,json=entryFunctionFilter,proto3,oneof" json:"entry_function_filter,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserTransactionPayloadFilter) Reset() {
	*x = UserTransactionPayloadFilter{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTransactionPayloadFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTransactionPayloadFilter) ProtoMessage() {}

func (x *UserTransactionPayloadFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTransactionPayloadFilter.ProtoReflect.Descriptor instead.
func (*UserTransactionPayloadFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{4}
}

func (x *UserTransactionPayloadFilter) GetEntryFunctionFilter() *EntryFunctionFilter {
	if x != nil {
		return x.EntryFunctionFilter
	}
	return nil
}

type UserTransactionFilter struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Sender        *string                       `protobuf:"bytes,1,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	PayloadFilter *UserTransactionPayloadFilter `protobuf:"bytes,2,opt,name=payload_filter,json=payloadFilter,proto3,oneof" json:"payload_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTransactionFilter) Reset() {
	*x = UserTransactionFilter{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTransactionFilter) ProtoMessage() {}

func (x *UserTransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTransactionFilter.ProtoReflect.Descriptor instead.
func (*UserTransactionFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{5}
}

func (x *UserTransactionFilter) GetSender() string {
	if x != nil && x.Sender != nil {
		return *x.Sender
	}
	return ""
}

func (x *UserTransactionFilter) GetPayloadFilter() *UserTransactionPayloadFilter {
	if x != nil {
		return x.PayloadFilter
	}
	return nil
}

type MoveStructTagFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *string                `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Module        *string                `protobuf:"bytes,2,opt,name=module,proto3,oneof" json:"module,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveStructTagFilter) Reset() {
	*x = MoveStructTagFilter{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveStructTagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveStructTagFilter) ProtoMessage() {}

func (x *MoveStructTagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveStructTagFilter.ProtoReflect.Descriptor instead.
func (*MoveStructTagFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{6}
}

func (x *MoveStructTagFilter) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *MoveStructTagFilter) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

func (x *MoveStructTagFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type EventFilter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StructType          *MoveStructTagFilter   `protobuf:"bytes,1,opt,name=struct_type,json=structType,proto3,oneof" json:"struct_type,omitempty"`
	DataSubstringFilter *string                `protobuf:"bytes,2,opt,name=data_substring_filter,json=dataSubstringFilter,proto3,oneof" json:"data_substring_filter,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{7}
}

func (x *EventFilter) GetStructType() *MoveStructTagFilter {
	if x != nil {
		return x.StructType
	}
	return nil
}

func (x *EventFilter) GetDataSubstringFilter() string {
	if x != nil && x.DataSubstringFilter != nil {
		return *x.DataSubstringFilter
	}
	return ""
}

type APIFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*APIFilter_TransactionRootFilter
	//	*APIFilter_UserTransactionFilter
	//	*APIFilter_EventFilter
	Filter        isAPIFilter_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIFilter) Reset() {
	*x = APIFilter{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIFilter) ProtoMessage() {}

func (x *APIFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIFilter.ProtoReflect.Descriptor instead.
func (*APIFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{8}
}

func (x *APIFilter) GetFilter() isAPIFilter_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *APIFilter) GetTransactionRootFilter() *TransactionRootFilter {
	if x != nil {
		if x, ok := x.Filter.(*APIFilter_TransactionRootFilter); ok {
			return x.TransactionRootFilter
		}
	}
	return nil
}

func (x *APIFilter) GetUserTransactionFilter() *UserTransactionFilter {
	if x != nil {
		if x, ok := x.Filter.(*APIFilter_UserTransactionFilter); ok {
			return x.UserTransactionFilter
		}
	}
	return nil
}

func (x *APIFilter) GetEventFilter() *EventFilter {
	if x != nil {
		if x, ok := x.Filter.(*APIFilter_EventFilter); ok {
			return x.EventFilter
		}
	}
	return nil
}

type isAPIFilter_Filter interface {
	isAPIFilter_Filter()
}

type APIFilter_TransactionRootFilter struct {
	TransactionRootFilter *TransactionRootFilter `protobuf:"bytes,1,opt,name=transaction_root_filter,json=transactionRootFilter,proto3,oneof"`
}

type APIFilter_UserTransactionFilter struct {
	UserTransactionFilter *UserTransactionFilter `protobuf:"bytes,2,opt,name=user_transaction_filter,json=userTransactionFilter,proto3,oneof"`
}

type APIFilter_EventFilter struct {
	EventFilter *EventFilter `protobuf:"bytes,3,opt,name=event_filter,json=eventFilter,proto3,oneof"`
}

func (*APIFilter_TransactionRootFilter) isAPIFilter_Filter() {}

func (*APIFilter_UserTransactionFilter) isAPIFilter_Filter() {}

func (*APIFilter_EventFilter) isAPIFilter_Filter() {}

type BooleanTransactionFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*BooleanTransactionFilter_ApiFilter
	//	*BooleanTransactionFilter_LogicalAnd
	//	*BooleanTransactionFilter_LogicalOr
	//	*BooleanTransactionFilter_LogicalNot
	Filter        isBooleanTransactionFilter_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanTransactionFilter) Reset() {
	*x = BooleanTransactionFilter{}
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanTransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanTransactionFilter) ProtoMessage() {}

func (x *BooleanTransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanTransactionFilter.ProtoReflect.Descriptor instead.
func (*BooleanTransactionFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{9}
}

func (x *BooleanTransactionFilter) GetFilter() isBooleanTransactionFilter_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *BooleanTransactionFilter) GetApiFilter() *APIFilter {
	if x != nil {
		if x, ok := x.Filter.(*BooleanTransactionFilter_ApiFilter); ok {
			return x.ApiFilter
		}
	}
	return nil
}

func (x *BooleanTransactionFilter) GetLogicalAnd() *LogicalAndFilters {
	if x != nil {
		if x, ok := x.Filter.(*BooleanTransactionFilter_LogicalAnd); ok {
			return x.LogicalAnd
		}
	}
	return nil
}

func (x *BooleanTransactionFilter) GetLogicalOr() *LogicalOrFilters {
	if x != nil {
		if x, ok := x.Filter.(*BooleanTransactionFilter_LogicalOr); ok {
			return x.LogicalOr
		}
	}
	return nil
}

func (x *BooleanTransactionFilter) GetLogicalNot() *BooleanTransactionFilter {
	if x != nil {
		if x, ok := x.Filter.(*BooleanTransactionFilter_LogicalNot); ok {
			return x.LogicalNot
		}
	}
	return nil
}

type isBooleanTransactionFilter_Filter interface {
	isBooleanTransactionFilter_Filter()
}

type BooleanTransactionFilter_ApiFilter struct {
	ApiFilter *APIFilter `protobuf:"bytes,1,opt,name=api_filter,json=apiFilter,proto3,oneof"`
}

type BooleanTransactionFilter_LogicalAnd struct {
	LogicalAnd *LogicalAndFilters `protobuf:"bytes,2,opt,name=logical_and,json=logicalAnd,proto3,oneof"`
}

type BooleanTransactionFilter_LogicalOr struct {
	LogicalOr *LogicalOrFilters `protobuf:"bytes,3,opt,name=logical_or,json=logicalOr,proto3,oneof"`
}

type BooleanTransactionFilter_LogicalNot struct {
	LogicalNot *BooleanTransactionFilter `protobuf:"bytes,4,opt,name=logical_not,json=logicalNot,proto3,oneof"`
}

func (*BooleanTransactionFilter_ApiFilter) isBooleanTransactionFilter_Filter() {}

func (*BooleanTransactionFilter_LogicalAnd) isBooleanTransactionFilter_Filter() {}

func (*BooleanTransactionFilter_LogicalOr) isBooleanTransactionFilter_Filter() {}

func (*BooleanTransactionFilter_LogicalNot) isBooleanTransactionFilter_Filter() {}

var File_aptos_indexer_v1_filter_proto protoreflect.FileDescriptor

const file_aptos_indexer_v1_filter_proto_rawDesc = "" +
	"\n" +
	"\x1daptos/indexer/v1/filter.proto\x12\x10aptos.indexer.v1\x1a&aptos/transaction/v1/transaction.proto\"Y\n" +
	"\x11LogicalAndFilters\x12D\n" +
	"\afilters\x18\x01 \x03(\v2*.aptos.indexer.v1.BooleanTransactionFilterR\afilters\"X\n" +
	"\x10LogicalOrFilters\x12D\n" +
	"\afilters\x18\x01 \x03(\v2*.aptos.indexer.v1.BooleanTransactionFilterR\afilters\"\xba\x01\n" +
	"\x15TransactionRootFilter\x12\x1d\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x88\x01\x01\x12a\n" +
	"\x10transaction_type\x18\x02 \x01(\x0e21.aptos.transaction.v1.Transaction.TransactionTypeH\x01R\x0ftransactionType\x88\x01\x01B\n" +
	"\n" +
	"\b_successB\x13\n" +
	"\x11_transaction_type\"\xa4\x01\n" +
	"\x13EntryFunctionFilter\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01\x12$\n" +
	"\vmodule_name\x18\x02 \x01(\tH\x01R\n" +
	"moduleName\x88\x01\x01\x12\x1f\n" +
	"\bfunction\x18\x03 \x01(\tH\x02R\bfunction\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\x0e\n" +
	"\f_module_nameB\v\n" +
	"\t_function\"\x98\x01\n" +
	"\x1cUserTransactionPayloadFilter\x12^\n" +
	"\x15entry_function_filter\x18\x01 \x01(\v2%.aptos.indexer.v1.EntryFunctionFilterH\x00R\x13entryFunctionFilter\x88\x01\x01B\x18\n" +
	"\x16_entry_function_filter\"\xae\x01\n" +
	"\x15UserTransactionFilter\x12\x1b\n" +
	"\x06sender\x18\x01 \x01(\tH\x00R\x06sender\x88\x01\x01\x12Z\n" +
	"\x0epayload_filter\x18\x02 \x01(\v2..aptos.indexer.v1.UserTransactionPayloadFilterH\x01R\rpayloadFilter\x88\x01\x01B\t\n" +
	"\a_senderB\x11\n" +
	"\x0f_payload_filter\"\x8a\x01\n" +
	"\x13MoveStructTagFilter\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x1b\n" +
	"\x06module\x18\x02 \x01(\tH\x01R\x06module\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\t\n" +
	"\a_moduleB\a\n" +
	"\x05_name\"\xbd\x01\n" +
	"\vEventFilter\x12K\n" +
	"\vstruct_type\x18\x01 \x01(\v2%.aptos.indexer.v1.MoveStructTagFilterH\x00R\n" +
	"structType\x88\x01\x01\x127\n" +
	"\x15data_substring_filter\x18\x02 \x01(\tH\x01R\x13dataSubstringFilter\x88\x01\x01B\x0e\n" +
	"\f_struct_typeB\x18\n" +
	"\x16_data_substring_filter\"\x9f\x02\n" +
	"\tAPIFilter\x12a\n" +
	"\x17transaction_root_filter\x18\x01 \x01(\v2'.aptos.indexer.v1.TransactionRootFilterH\x00R\x15transactionRootFilter\x12a\n" +
	"\x17user_transaction_filter\x18\x02 \x01(\v2'.aptos.indexer.v1.UserTransactionFilterH\x00R\x15userTransactionFilter\x12B\n" +
	"\fevent_filter\x18\x03 \x01(\v2\x1d.aptos.indexer.v1.EventFilterH\x00R\veventFilterB\b\n" +
	"\x06filter\"\xbe\x02\n" +
	"\x18BooleanTransactionFilter\x12<\n" +
	"\n" +
	"api_filter\x18\x01 \x01(\v2\x1b.aptos.indexer.v1.APIFilterH\x00R\tapiFilter\x12F\n" +
	"\vlogical_and\x18\x02 \x01(\v2#.aptos.indexer.v1.LogicalAndFiltersH\x00R\n" +
	"logicalAnd\x12C\n" +
	"\n" +
	"logical_or\x18\x03 \x01(\v2\".aptos.indexer.v1.LogicalOrFiltersH\x00R\tlogicalOr\x12M\n" +
	"\vlogical_not\x18\x04 \x01(\v2*.aptos.indexer.v1.BooleanTransactionFilterH\x00R\n" +
	"logicalNotB\b\n" +
	"\x06filterBBZ@github.com/xiaobaiskill/aptos-grpc-go/aptos/indexer/v1;indexerv1b\x06proto3"

var (
	file_aptos_indexer_v1_filter_proto_rawDescOnce sync.Once
	file_aptos_indexer_v1_filter_proto_rawDescData []byte
)

func file_aptos_indexer_v1_filter_proto_rawDescGZIP() []byte {
	file_aptos_indexer_v1_filter_proto_rawDescOnce.Do(func() {
		file_aptos_indexer_v1_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aptos_indexer_v1_filter_proto_rawDesc), len(file_aptos_indexer_v1_filter_proto_rawDesc)))
	})
	return file_aptos_indexer_v1_filter_proto_rawDescData
}

var file_aptos_indexer_v1_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aptos_indexer_v1_filter_proto_goTypes = []any{
	(*LogicalAndFilters)(nil),            // 0: aptos.indexer.v1.LogicalAndFilters
	(*LogicalOrFilters)(nil),             // 1: aptos.indexer.v1.LogicalOrFilters
	(*TransactionRootFilter)(nil),        // 2: aptos.indexer.v1.TransactionRootFilter
	(*EntryFunctionFilter)(nil),          // 3: aptos.indexer.v1.EntryFunctionFilter
	(*UserTransactionPayloadFilter)(nil), // 4: aptos.indexer.v1.UserTransactionPayloadFilter
	(*UserTransactionFilter)(nil),        // 5: aptos.indexer.v1.UserTransactionFilter
	(*MoveStructTagFilter)(nil),          // 6: aptos.indexer.v1.MoveStructTagFilter
	(*EventFilter)(nil),                  // 7: aptos.indexer.v1.EventFilter
	(*APIFilter)(nil),                    // 8: aptos.indexer.v1.APIFilter
	(*BooleanTransactionFilter)(nil),     // 9: aptos.indexer.v1.BooleanTransactionFilter
	(v1.Transaction_TransactionType)(0),  // 10: aptos.transaction.v1.Transaction.TransactionType
}
var file_aptos_indexer_v1_filter_proto_depIdxs = []int32{
	9,  // 0: aptos.indexer.v1.LogicalAndFilters.filters:type_name -> aptos.indexer.v1.BooleanTransactionFilter
	9,  // 1: aptos.indexer.v1.LogicalOrFilters.filters:type_name -> aptos.indexer.v1.BooleanTransactionFilter
	10, // 2: aptos.indexer.v1.TransactionRootFilter.transaction_type:type_name -> aptos.transaction.v1.Transaction.TransactionType
	3,  // 3: aptos.indexer.v1.UserTransactionPayloadFilter.entry_function_filter:type_name -> aptos.indexer.v1.EntryFunctionFilter
	4,  // 4: aptos.indexer.v1.UserTransactionFilter.payload_filter:type_name -> aptos.indexer.v1.UserTransactionPayloadFilter
	6,  // 5: aptos.indexer.v1.EventFilter.struct_type:type_name -> aptos.indexer.v1.MoveStructTagFilter
	2,  // 6: aptos.indexer.v1.APIFilter.transaction_root_filter:type_name -> aptos.indexer.v1.TransactionRootFilter
	5,  // 7: aptos.indexer.v1.APIFilter.user_transaction_filter:type_name -> aptos.indexer.v1.UserTransactionFilter
	7,  // 8: aptos.indexer.v1.APIFilter.event_filter:type_name -> aptos.indexer.v1.EventFilter
	8,  // 9: aptos.indexer.v1.BooleanTransactionFilter.api_filter:type_name -> aptos.indexer.v1.APIFilter
	0,  // 10: aptos.indexer.v1.BooleanTransactionFilter.logical_and:type_name -> aptos.indexer.v1.LogicalAndFilters
	1,  // 11: aptos.indexer.v1.BooleanTransactionFilter.logical_or:type_name -> aptos.indexer.v1.LogicalOrFilters
	9,  // 12: aptos.indexer.v1.BooleanTransactionFilter.logical_not:type_name -> aptos.indexer.v1.BooleanTransactionFilter
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_aptos_indexer_v1_filter_proto_init() }
func file_aptos_indexer_v1_filter_proto_init() {
	if File_aptos_indexer_v1_filter_proto != nil {
		return
	}
	file_aptos_indexer_v1_filter_proto_msgTypes[2].OneofWrappers = []any{}
	file_aptos_indexer_v1_filter_proto_msgTypes[3].OneofWrappers = []any{}
	file_aptos_indexer_v1_filter_proto_msgTypes[4].OneofWrappers = []any{}
	file_aptos_indexer_v1_filter_proto_msgTypes[5].OneofWrappers = []any{}
	file_aptos_indexer_v1_filter_proto_msgTypes[6].OneofWrappers = []any{}
	file_aptos_indexer_v1_filter_proto_msgTypes[7].OneofWrappers = []any{}
	file_aptos_indexer_v1_filter_proto_msgTypes[8].OneofWrappers = []any{
		(*APIFilter_TransactionRootFilter)(nil),
		(*APIFilter_UserTransactionFilter)(nil),
		(*APIFilter_EventFilter)(nil),
	}
	file_aptos_indexer_v1_filter_proto_msgTypes[9].OneofWrappers = []any{
		(*BooleanTransactionFilter_ApiFilter)(nil),
		(*BooleanTransactionFilter_LogicalAnd)(nil),
		(*BooleanTransactionFilter_LogicalOr)(nil),
		(*BooleanTransactionFilter_LogicalNot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aptos_indexer_v1_filter_proto_rawDesc), len(file_aptos_indexer_v1_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aptos_indexer_v1_filter_proto_goTypes,
		DependencyIndexes: file_aptos_indexer_v1_filter_proto_depIdxs,
		MessageInfos:      file_aptos_indexer_v1_filter_proto_msgTypes,
	}.Build()
	File_aptos_indexer_v1_filter_proto = out.File
	file_aptos_indexer_v1_filter_proto_goTypes = nil
	file_aptos_indexer_v1_filter_proto_depIdxs = nil
}
