// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: aptos/indexer/v1/grpc.proto

package indexerv1

import (
	timestamp "github.com/xiaobaiskill/aptos-grpc-go/aptos/util/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamProgressSampleProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProgressSampleProto) Reset() {
	*x = StreamProgressSampleProto{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProgressSampleProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProgressSampleProto) ProtoMessage() {}

func (x *StreamProgressSampleProto) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProgressSampleProto.ProtoReflect.Descriptor instead.
func (*StreamProgressSampleProto) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *StreamProgressSampleProto) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StreamProgressSampleProto) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StreamProgressSampleProto) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type StreamProgress struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Samples       []*StreamProgressSampleProto `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProgress) Reset() {
	*x = StreamProgress{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProgress) ProtoMessage() {}

func (x *StreamProgress) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProgress.ProtoReflect.Descriptor instead.
func (*StreamProgress) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *StreamProgress) GetSamples() []*StreamProgressSampleProto {
	if x != nil {
		return x.Samples
	}
	return nil
}

type ActiveStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	StartVersion  uint64                 `protobuf:"varint,3,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	EndVersion    *uint64                `protobuf:"varint,4,opt,name=end_version,json=endVersion,proto3,oneof" json:"end_version,omitempty"`
	Progress      *StreamProgress        `protobuf:"bytes,5,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveStream) Reset() {
	*x = ActiveStream{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveStream) ProtoMessage() {}

func (x *ActiveStream) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveStream.ProtoReflect.Descriptor instead.
func (*ActiveStream) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ActiveStream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActiveStream) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ActiveStream) GetStartVersion() uint64 {
	if x != nil {
		return x.StartVersion
	}
	return 0
}

func (x *ActiveStream) GetEndVersion() uint64 {
	if x != nil && x.EndVersion != nil {
		return *x.EndVersion
	}
	return 0
}

func (x *ActiveStream) GetProgress() *StreamProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveStreams []*ActiveStream        `protobuf:"bytes,1,rep,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *StreamInfo) GetActiveStreams() []*ActiveStream {
	if x != nil {
		return x.ActiveStreams
	}
	return nil
}

type LiveDataServiceInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChainId            uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Timestamp          *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	KnownLatestVersion *uint64                `protobuf:"varint,3,opt,name=known_latest_version,json=knownLatestVersion,proto3,oneof" json:"known_latest_version,omitempty"`
	StreamInfo         *StreamInfo            `protobuf:"bytes,4,opt,name=stream_info,json=streamInfo,proto3,oneof" json:"stream_info,omitempty"`
	// If not present, it means the data service is not available to serve anything yet.
	MinServableVersion *uint64 `protobuf:"varint,5,opt,name=min_servable_version,json=minServableVersion,proto3,oneof" json:"min_servable_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LiveDataServiceInfo) Reset() {
	*x = LiveDataServiceInfo{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveDataServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveDataServiceInfo) ProtoMessage() {}

func (x *LiveDataServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveDataServiceInfo.ProtoReflect.Descriptor instead.
func (*LiveDataServiceInfo) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *LiveDataServiceInfo) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *LiveDataServiceInfo) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LiveDataServiceInfo) GetKnownLatestVersion() uint64 {
	if x != nil && x.KnownLatestVersion != nil {
		return *x.KnownLatestVersion
	}
	return 0
}

func (x *LiveDataServiceInfo) GetStreamInfo() *StreamInfo {
	if x != nil {
		return x.StreamInfo
	}
	return nil
}

func (x *LiveDataServiceInfo) GetMinServableVersion() uint64 {
	if x != nil && x.MinServableVersion != nil {
		return *x.MinServableVersion
	}
	return 0
}

type HistoricalDataServiceInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChainId            uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Timestamp          *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	KnownLatestVersion *uint64                `protobuf:"varint,3,opt,name=known_latest_version,json=knownLatestVersion,proto3,oneof" json:"known_latest_version,omitempty"`
	StreamInfo         *StreamInfo            `protobuf:"bytes,4,opt,name=stream_info,json=streamInfo,proto3,oneof" json:"stream_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HistoricalDataServiceInfo) Reset() {
	*x = HistoricalDataServiceInfo{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalDataServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalDataServiceInfo) ProtoMessage() {}

func (x *HistoricalDataServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalDataServiceInfo.ProtoReflect.Descriptor instead.
func (*HistoricalDataServiceInfo) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *HistoricalDataServiceInfo) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *HistoricalDataServiceInfo) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HistoricalDataServiceInfo) GetKnownLatestVersion() uint64 {
	if x != nil && x.KnownLatestVersion != nil {
		return *x.KnownLatestVersion
	}
	return 0
}

func (x *HistoricalDataServiceInfo) GetStreamInfo() *StreamInfo {
	if x != nil {
		return x.StreamInfo
	}
	return nil
}

type FullnodeInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChainId            uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Timestamp          *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	KnownLatestVersion *uint64                `protobuf:"varint,3,opt,name=known_latest_version,json=knownLatestVersion,proto3,oneof" json:"known_latest_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FullnodeInfo) Reset() {
	*x = FullnodeInfo{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullnodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullnodeInfo) ProtoMessage() {}

func (x *FullnodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullnodeInfo.ProtoReflect.Descriptor instead.
func (*FullnodeInfo) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *FullnodeInfo) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *FullnodeInfo) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FullnodeInfo) GetKnownLatestVersion() uint64 {
	if x != nil && x.KnownLatestVersion != nil {
		return *x.KnownLatestVersion
	}
	return 0
}

type GrpcManagerInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChainId            uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Timestamp          *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	KnownLatestVersion *uint64                `protobuf:"varint,3,opt,name=known_latest_version,json=knownLatestVersion,proto3,oneof" json:"known_latest_version,omitempty"`
	MasterAddress      *string                `protobuf:"bytes,4,opt,name=master_address,json=masterAddress,proto3,oneof" json:"master_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GrpcManagerInfo) Reset() {
	*x = GrpcManagerInfo{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcManagerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcManagerInfo) ProtoMessage() {}

func (x *GrpcManagerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcManagerInfo.ProtoReflect.Descriptor instead.
func (*GrpcManagerInfo) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *GrpcManagerInfo) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GrpcManagerInfo) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GrpcManagerInfo) GetKnownLatestVersion() uint64 {
	if x != nil && x.KnownLatestVersion != nil {
		return *x.KnownLatestVersion
	}
	return 0
}

func (x *GrpcManagerInfo) GetMasterAddress() string {
	if x != nil && x.MasterAddress != nil {
		return *x.MasterAddress
	}
	return ""
}

type ServiceInfo struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address *string                `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// Types that are valid to be assigned to Info:
	//
	//	*ServiceInfo_LiveDataServiceInfo
	//	*ServiceInfo_HistoricalDataServiceInfo
	//	*ServiceInfo_FullnodeInfo
	//	*ServiceInfo_GrpcManagerInfo
	Info          isServiceInfo_Info `protobuf_oneof:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *ServiceInfo) GetInfo() isServiceInfo_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ServiceInfo) GetLiveDataServiceInfo() *LiveDataServiceInfo {
	if x != nil {
		if x, ok := x.Info.(*ServiceInfo_LiveDataServiceInfo); ok {
			return x.LiveDataServiceInfo
		}
	}
	return nil
}

func (x *ServiceInfo) GetHistoricalDataServiceInfo() *HistoricalDataServiceInfo {
	if x != nil {
		if x, ok := x.Info.(*ServiceInfo_HistoricalDataServiceInfo); ok {
			return x.HistoricalDataServiceInfo
		}
	}
	return nil
}

func (x *ServiceInfo) GetFullnodeInfo() *FullnodeInfo {
	if x != nil {
		if x, ok := x.Info.(*ServiceInfo_FullnodeInfo); ok {
			return x.FullnodeInfo
		}
	}
	return nil
}

func (x *ServiceInfo) GetGrpcManagerInfo() *GrpcManagerInfo {
	if x != nil {
		if x, ok := x.Info.(*ServiceInfo_GrpcManagerInfo); ok {
			return x.GrpcManagerInfo
		}
	}
	return nil
}

type isServiceInfo_Info interface {
	isServiceInfo_Info()
}

type ServiceInfo_LiveDataServiceInfo struct {
	LiveDataServiceInfo *LiveDataServiceInfo `protobuf:"bytes,2,opt,name=live_data_service_info,json=liveDataServiceInfo,proto3,oneof"`
}

type ServiceInfo_HistoricalDataServiceInfo struct {
	HistoricalDataServiceInfo *HistoricalDataServiceInfo `protobuf:"bytes,3,opt,name=historical_data_service_info,json=historicalDataServiceInfo,proto3,oneof"`
}

type ServiceInfo_FullnodeInfo struct {
	FullnodeInfo *FullnodeInfo `protobuf:"bytes,4,opt,name=fullnode_info,json=fullnodeInfo,proto3,oneof"`
}

type ServiceInfo_GrpcManagerInfo struct {
	GrpcManagerInfo *GrpcManagerInfo `protobuf:"bytes,5,opt,name=grpc_manager_info,json=grpcManagerInfo,proto3,oneof"`
}

func (*ServiceInfo_LiveDataServiceInfo) isServiceInfo_Info() {}

func (*ServiceInfo_HistoricalDataServiceInfo) isServiceInfo_Info() {}

func (*ServiceInfo_FullnodeInfo) isServiceInfo_Info() {}

func (*ServiceInfo_GrpcManagerInfo) isServiceInfo_Info() {}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceInfo   *ServiceInfo           `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3,oneof" json:"service_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatRequest) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

type HeartbeatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	KnownLatestVersion *uint64                `protobuf:"varint,1,opt,name=known_latest_version,json=knownLatestVersion,proto3,oneof" json:"known_latest_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResponse) GetKnownLatestVersion() uint64 {
	if x != nil && x.KnownLatestVersion != nil {
		return *x.KnownLatestVersion
	}
	return 0
}

type PingDataServiceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	KnownLatestVersion *uint64                `protobuf:"varint,1,opt,name=known_latest_version,json=knownLatestVersion,proto3,oneof" json:"known_latest_version,omitempty"`
	// `true` for live data service, `false` for historical data service.
	PingLiveDataService bool `protobuf:"varint,2,opt,name=ping_live_data_service,json=pingLiveDataService,proto3" json:"ping_live_data_service,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PingDataServiceRequest) Reset() {
	*x = PingDataServiceRequest{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDataServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDataServiceRequest) ProtoMessage() {}

func (x *PingDataServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDataServiceRequest.ProtoReflect.Descriptor instead.
func (*PingDataServiceRequest) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *PingDataServiceRequest) GetKnownLatestVersion() uint64 {
	if x != nil && x.KnownLatestVersion != nil {
		return *x.KnownLatestVersion
	}
	return 0
}

func (x *PingDataServiceRequest) GetPingLiveDataService() bool {
	if x != nil {
		return x.PingLiveDataService
	}
	return false
}

type PingDataServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Info:
	//
	//	*PingDataServiceResponse_LiveDataServiceInfo
	//	*PingDataServiceResponse_HistoricalDataServiceInfo
	Info          isPingDataServiceResponse_Info `protobuf_oneof:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDataServiceResponse) Reset() {
	*x = PingDataServiceResponse{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDataServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDataServiceResponse) ProtoMessage() {}

func (x *PingDataServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDataServiceResponse.ProtoReflect.Descriptor instead.
func (*PingDataServiceResponse) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *PingDataServiceResponse) GetInfo() isPingDataServiceResponse_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *PingDataServiceResponse) GetLiveDataServiceInfo() *LiveDataServiceInfo {
	if x != nil {
		if x, ok := x.Info.(*PingDataServiceResponse_LiveDataServiceInfo); ok {
			return x.LiveDataServiceInfo
		}
	}
	return nil
}

func (x *PingDataServiceResponse) GetHistoricalDataServiceInfo() *HistoricalDataServiceInfo {
	if x != nil {
		if x, ok := x.Info.(*PingDataServiceResponse_HistoricalDataServiceInfo); ok {
			return x.HistoricalDataServiceInfo
		}
	}
	return nil
}

type isPingDataServiceResponse_Info interface {
	isPingDataServiceResponse_Info()
}

type PingDataServiceResponse_LiveDataServiceInfo struct {
	LiveDataServiceInfo *LiveDataServiceInfo `protobuf:"bytes,1,opt,name=live_data_service_info,json=liveDataServiceInfo,proto3,oneof"`
}

type PingDataServiceResponse_HistoricalDataServiceInfo struct {
	HistoricalDataServiceInfo *HistoricalDataServiceInfo `protobuf:"bytes,2,opt,name=historical_data_service_info,json=historicalDataServiceInfo,proto3,oneof"`
}

func (*PingDataServiceResponse_LiveDataServiceInfo) isPingDataServiceResponse_Info() {}

func (*PingDataServiceResponse_HistoricalDataServiceInfo) isPingDataServiceResponse_Info() {}

type GetDataServiceForRequestRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserRequest   *GetTransactionsRequest `protobuf:"bytes,1,opt,name=user_request,json=userRequest,proto3,oneof" json:"user_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataServiceForRequestRequest) Reset() {
	*x = GetDataServiceForRequestRequest{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataServiceForRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataServiceForRequestRequest) ProtoMessage() {}

func (x *GetDataServiceForRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataServiceForRequestRequest.ProtoReflect.Descriptor instead.
func (*GetDataServiceForRequestRequest) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *GetDataServiceForRequestRequest) GetUserRequest() *GetTransactionsRequest {
	if x != nil {
		return x.UserRequest
	}
	return nil
}

type GetDataServiceForRequestResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DataServiceAddress string                 `protobuf:"bytes,1,opt,name=data_service_address,json=dataServiceAddress,proto3" json:"data_service_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetDataServiceForRequestResponse) Reset() {
	*x = GetDataServiceForRequestResponse{}
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataServiceForRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataServiceForRequestResponse) ProtoMessage() {}

func (x *GetDataServiceForRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataServiceForRequestResponse.ProtoReflect.Descriptor instead.
func (*GetDataServiceForRequestResponse) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetDataServiceForRequestResponse) GetDataServiceAddress() string {
	if x != nil {
		return x.DataServiceAddress
	}
	return ""
}

var File_aptos_indexer_v1_grpc_proto protoreflect.FileDescriptor

const file_aptos_indexer_v1_grpc_proto_rawDesc = "" +
	"\n" +
	"\x1baptos/indexer/v1/grpc.proto\x12\x10aptos.indexer.v1\x1a\x1faptos/indexer/v1/raw_data.proto\x1a$aptos/util/timestamp/timestamp.proto\"\xa6\x01\n" +
	"\x19StreamProgressSampleProto\x12B\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1f.aptos.util.timestamp.TimestampH\x00R\ttimestamp\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytesB\f\n" +
	"\n" +
	"_timestamp\"W\n" +
	"\x0eStreamProgress\x12E\n" +
	"\asamples\x18\x01 \x03(\v2+.aptos.indexer.v1.StreamProgressSampleProtoR\asamples\"\x9d\x02\n" +
	"\fActiveStream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1f.aptos.util.timestamp.TimestampH\x00R\tstartTime\x88\x01\x01\x12#\n" +
	"\rstart_version\x18\x03 \x01(\x04R\fstartVersion\x12$\n" +
	"\vend_version\x18\x04 \x01(\x04H\x01R\n" +
	"endVersion\x88\x01\x01\x12A\n" +
	"\bprogress\x18\x05 \x01(\v2 .aptos.indexer.v1.StreamProgressH\x02R\bprogress\x88\x01\x01B\r\n" +
	"\v_start_timeB\x0e\n" +
	"\f_end_versionB\v\n" +
	"\t_progress\"S\n" +
	"\n" +
	"StreamInfo\x12E\n" +
	"\x0eactive_streams\x18\x01 \x03(\v2\x1e.aptos.indexer.v1.ActiveStreamR\ractiveStreams\"\xf6\x02\n" +
	"\x13LiveDataServiceInfo\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12B\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1f.aptos.util.timestamp.TimestampH\x00R\ttimestamp\x88\x01\x01\x125\n" +
	"\x14known_latest_version\x18\x03 \x01(\x04H\x01R\x12knownLatestVersion\x88\x01\x01\x12B\n" +
	"\vstream_info\x18\x04 \x01(\v2\x1c.aptos.indexer.v1.StreamInfoH\x02R\n" +
	"streamInfo\x88\x01\x01\x125\n" +
	"\x14min_servable_version\x18\x05 \x01(\x04H\x03R\x12minServableVersion\x88\x01\x01B\f\n" +
	"\n" +
	"_timestampB\x17\n" +
	"\x15_known_latest_versionB\x0e\n" +
	"\f_stream_infoB\x17\n" +
	"\x15_min_servable_version\"\xac\x02\n" +
	"\x19HistoricalDataServiceInfo\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12B\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1f.aptos.util.timestamp.TimestampH\x00R\ttimestamp\x88\x01\x01\x125\n" +
	"\x14known_latest_version\x18\x03 \x01(\x04H\x01R\x12knownLatestVersion\x88\x01\x01\x12B\n" +
	"\vstream_info\x18\x04 \x01(\v2\x1c.aptos.indexer.v1.StreamInfoH\x02R\n" +
	"streamInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_timestampB\x17\n" +
	"\x15_known_latest_versionB\x0e\n" +
	"\f_stream_info\"\xcb\x01\n" +
	"\fFullnodeInfo\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12B\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1f.aptos.util.timestamp.TimestampH\x00R\ttimestamp\x88\x01\x01\x125\n" +
	"\x14known_latest_version\x18\x03 \x01(\x04H\x01R\x12knownLatestVersion\x88\x01\x01B\f\n" +
	"\n" +
	"_timestampB\x17\n" +
	"\x15_known_latest_version\"\x8d\x02\n" +
	"\x0fGrpcManagerInfo\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12B\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1f.aptos.util.timestamp.TimestampH\x00R\ttimestamp\x88\x01\x01\x125\n" +
	"\x14known_latest_version\x18\x03 \x01(\x04H\x01R\x12knownLatestVersion\x88\x01\x01\x12*\n" +
	"\x0emaster_address\x18\x04 \x01(\tH\x02R\rmasterAddress\x88\x01\x01B\f\n" +
	"\n" +
	"_timestampB\x17\n" +
	"\x15_known_latest_versionB\x11\n" +
	"\x0f_master_address\"\xa6\x03\n" +
	"\vServiceInfo\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x01R\aaddress\x88\x01\x01\x12\\\n" +
	"\x16live_data_service_info\x18\x02 \x01(\v2%.aptos.indexer.v1.LiveDataServiceInfoH\x00R\x13liveDataServiceInfo\x12n\n" +
	"\x1chistorical_data_service_info\x18\x03 \x01(\v2+.aptos.indexer.v1.HistoricalDataServiceInfoH\x00R\x19historicalDataServiceInfo\x12E\n" +
	"\rfullnode_info\x18\x04 \x01(\v2\x1e.aptos.indexer.v1.FullnodeInfoH\x00R\ffullnodeInfo\x12O\n" +
	"\x11grpc_manager_info\x18\x05 \x01(\v2!.aptos.indexer.v1.GrpcManagerInfoH\x00R\x0fgrpcManagerInfoB\x06\n" +
	"\x04infoB\n" +
	"\n" +
	"\b_address\"j\n" +
	"\x10HeartbeatRequest\x12E\n" +
	"\fservice_info\x18\x01 \x01(\v2\x1d.aptos.indexer.v1.ServiceInfoH\x00R\vserviceInfo\x88\x01\x01B\x0f\n" +
	"\r_service_info\"c\n" +
	"\x11HeartbeatResponse\x125\n" +
	"\x14known_latest_version\x18\x01 \x01(\x04H\x00R\x12knownLatestVersion\x88\x01\x01B\x17\n" +
	"\x15_known_latest_version\"\x9d\x01\n" +
	"\x16PingDataServiceRequest\x125\n" +
	"\x14known_latest_version\x18\x01 \x01(\x04H\x00R\x12knownLatestVersion\x88\x01\x01\x123\n" +
	"\x16ping_live_data_service\x18\x02 \x01(\bR\x13pingLiveDataServiceB\x17\n" +
	"\x15_known_latest_version\"\xef\x01\n" +
	"\x17PingDataServiceResponse\x12\\\n" +
	"\x16live_data_service_info\x18\x01 \x01(\v2%.aptos.indexer.v1.LiveDataServiceInfoH\x00R\x13liveDataServiceInfo\x12n\n" +
	"\x1chistorical_data_service_info\x18\x02 \x01(\v2+.aptos.indexer.v1.HistoricalDataServiceInfoH\x00R\x19historicalDataServiceInfoB\x06\n" +
	"\x04info\"\x84\x01\n" +
	"\x1fGetDataServiceForRequestRequest\x12P\n" +
	"\fuser_request\x18\x01 \x01(\v2(.aptos.indexer.v1.GetTransactionsRequestH\x00R\vuserRequest\x88\x01\x01B\x0f\n" +
	"\r_user_request\"T\n" +
	" GetDataServiceForRequestResponse\x120\n" +
	"\x14data_service_address\x18\x01 \x01(\tR\x12dataServiceAddress2\xcc\x02\n" +
	"\vGrpcManager\x12T\n" +
	"\tHeartbeat\x12\".aptos.indexer.v1.HeartbeatRequest\x1a#.aptos.indexer.v1.HeartbeatResponse\x12c\n" +
	"\x0fGetTransactions\x12(.aptos.indexer.v1.GetTransactionsRequest\x1a&.aptos.indexer.v1.TransactionsResponse\x12\x81\x01\n" +
	"\x18GetDataServiceForRequest\x121.aptos.indexer.v1.GetDataServiceForRequestRequest\x1a2.aptos.indexer.v1.GetDataServiceForRequestResponse2\xd1\x01\n" +
	"\vDataService\x12[\n" +
	"\x04Ping\x12(.aptos.indexer.v1.PingDataServiceRequest\x1a).aptos.indexer.v1.PingDataServiceResponse\x12e\n" +
	"\x0fGetTransactions\x12(.aptos.indexer.v1.GetTransactionsRequest\x1a&.aptos.indexer.v1.TransactionsResponse0\x01BBZ@github.com/xiaobaiskill/aptos-grpc-go/aptos/indexer/v1;indexerv1b\x06proto3"

var (
	file_aptos_indexer_v1_grpc_proto_rawDescOnce sync.Once
	file_aptos_indexer_v1_grpc_proto_rawDescData []byte
)

func file_aptos_indexer_v1_grpc_proto_rawDescGZIP() []byte {
	file_aptos_indexer_v1_grpc_proto_rawDescOnce.Do(func() {
		file_aptos_indexer_v1_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aptos_indexer_v1_grpc_proto_rawDesc), len(file_aptos_indexer_v1_grpc_proto_rawDesc)))
	})
	return file_aptos_indexer_v1_grpc_proto_rawDescData
}

var file_aptos_indexer_v1_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_aptos_indexer_v1_grpc_proto_goTypes = []any{
	(*StreamProgressSampleProto)(nil),        // 0: aptos.indexer.v1.StreamProgressSampleProto
	(*StreamProgress)(nil),                   // 1: aptos.indexer.v1.StreamProgress
	(*ActiveStream)(nil),                     // 2: aptos.indexer.v1.ActiveStream
	(*StreamInfo)(nil),                       // 3: aptos.indexer.v1.StreamInfo
	(*LiveDataServiceInfo)(nil),              // 4: aptos.indexer.v1.LiveDataServiceInfo
	(*HistoricalDataServiceInfo)(nil),        // 5: aptos.indexer.v1.HistoricalDataServiceInfo
	(*FullnodeInfo)(nil),                     // 6: aptos.indexer.v1.FullnodeInfo
	(*GrpcManagerInfo)(nil),                  // 7: aptos.indexer.v1.GrpcManagerInfo
	(*ServiceInfo)(nil),                      // 8: aptos.indexer.v1.ServiceInfo
	(*HeartbeatRequest)(nil),                 // 9: aptos.indexer.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),                // 10: aptos.indexer.v1.HeartbeatResponse
	(*PingDataServiceRequest)(nil),           // 11: aptos.indexer.v1.PingDataServiceRequest
	(*PingDataServiceResponse)(nil),          // 12: aptos.indexer.v1.PingDataServiceResponse
	(*GetDataServiceForRequestRequest)(nil),  // 13: aptos.indexer.v1.GetDataServiceForRequestRequest
	(*GetDataServiceForRequestResponse)(nil), // 14: aptos.indexer.v1.GetDataServiceForRequestResponse
	(*timestamp.Timestamp)(nil),              // 15: aptos.util.timestamp.Timestamp
	(*GetTransactionsRequest)(nil),           // 16: aptos.indexer.v1.GetTransactionsRequest
	(*TransactionsResponse)(nil),             // 17: aptos.indexer.v1.TransactionsResponse
}
var file_aptos_indexer_v1_grpc_proto_depIdxs = []int32{
	15, // 0: aptos.indexer.v1.StreamProgressSampleProto.timestamp:type_name -> aptos.util.timestamp.Timestamp
	0,  // 1: aptos.indexer.v1.StreamProgress.samples:type_name -> aptos.indexer.v1.StreamProgressSampleProto
	15, // 2: aptos.indexer.v1.ActiveStream.start_time:type_name -> aptos.util.timestamp.Timestamp
	1,  // 3: aptos.indexer.v1.ActiveStream.progress:type_name -> aptos.indexer.v1.StreamProgress
	2,  // 4: aptos.indexer.v1.StreamInfo.active_streams:type_name -> aptos.indexer.v1.ActiveStream
	15, // 5: aptos.indexer.v1.LiveDataServiceInfo.timestamp:type_name -> aptos.util.timestamp.Timestamp
	3,  // 6: aptos.indexer.v1.LiveDataServiceInfo.stream_info:type_name -> aptos.indexer.v1.StreamInfo
	15, // 7: aptos.indexer.v1.HistoricalDataServiceInfo.timestamp:type_name -> aptos.util.timestamp.Timestamp
	3,  // 8: aptos.indexer.v1.HistoricalDataServiceInfo.stream_info:type_name -> aptos.indexer.v1.StreamInfo
	15, // 9: aptos.indexer.v1.FullnodeInfo.timestamp:type_name -> aptos.util.timestamp.Timestamp
	15, // 10: aptos.indexer.v1.GrpcManagerInfo.timestamp:type_name -> aptos.util.timestamp.Timestamp
	4,  // 11: aptos.indexer.v1.ServiceInfo.live_data_service_info:type_name -> aptos.indexer.v1.LiveDataServiceInfo
	5,  // 12: aptos.indexer.v1.ServiceInfo.historical_data_service_info:type_name -> aptos.indexer.v1.HistoricalDataServiceInfo
	6,  // 13: aptos.indexer.v1.ServiceInfo.fullnode_info:type_name -> aptos.indexer.v1.FullnodeInfo
	7,  // 14: aptos.indexer.v1.ServiceInfo.grpc_manager_info:type_name -> aptos.indexer.v1.GrpcManagerInfo
	8,  // 15: aptos.indexer.v1.HeartbeatRequest.service_info:type_name -> aptos.indexer.v1.ServiceInfo
	4,  // 16: aptos.indexer.v1.PingDataServiceResponse.live_data_service_info:type_name -> aptos.indexer.v1.LiveDataServiceInfo
	5,  // 17: aptos.indexer.v1.PingDataServiceResponse.historical_data_service_info:type_name -> aptos.indexer.v1.HistoricalDataServiceInfo
	16, // 18: aptos.indexer.v1.GetDataServiceForRequestRequest.user_request:type_name -> aptos.indexer.v1.GetTransactionsRequest
	9,  // 19: aptos.indexer.v1.GrpcManager.Heartbeat:input_type -> aptos.indexer.v1.HeartbeatRequest
	16, // 20: aptos.indexer.v1.GrpcManager.GetTransactions:input_type -> aptos.indexer.v1.GetTransactionsRequest
	13, // 21: aptos.indexer.v1.GrpcManager.GetDataServiceForRequest:input_type -> aptos.indexer.v1.GetDataServiceForRequestRequest
	11, // 22: aptos.indexer.v1.DataService.Ping:input_type -> aptos.indexer.v1.PingDataServiceRequest
	16, // 23: aptos.indexer.v1.DataService.GetTransactions:input_type -> aptos.indexer.v1.GetTransactionsRequest
	10, // 24: aptos.indexer.v1.GrpcManager.Heartbeat:output_type -> aptos.indexer.v1.HeartbeatResponse
	17, // 25: aptos.indexer.v1.GrpcManager.GetTransactions:output_type -> aptos.indexer.v1.TransactionsResponse
	14, // 26: aptos.indexer.v1.GrpcManager.GetDataServiceForRequest:output_type -> aptos.indexer.v1.GetDataServiceForRequestResponse
	12, // 27: aptos.indexer.v1.DataService.Ping:output_type -> aptos.indexer.v1.PingDataServiceResponse
	17, // 28: aptos.indexer.v1.DataService.GetTransactions:output_type -> aptos.indexer.v1.TransactionsResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_aptos_indexer_v1_grpc_proto_init() }
func file_aptos_indexer_v1_grpc_proto_init() {
	if File_aptos_indexer_v1_grpc_proto != nil {
		return
	}
	file_aptos_indexer_v1_raw_data_proto_init()
	file_aptos_indexer_v1_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[2].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[4].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[5].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[6].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[7].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[8].OneofWrappers = []any{
		(*ServiceInfo_LiveDataServiceInfo)(nil),
		(*ServiceInfo_HistoricalDataServiceInfo)(nil),
		(*ServiceInfo_FullnodeInfo)(nil),
		(*ServiceInfo_GrpcManagerInfo)(nil),
	}
	file_aptos_indexer_v1_grpc_proto_msgTypes[9].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[10].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[11].OneofWrappers = []any{}
	file_aptos_indexer_v1_grpc_proto_msgTypes[12].OneofWrappers = []any{
		(*PingDataServiceResponse_LiveDataServiceInfo)(nil),
		(*PingDataServiceResponse_HistoricalDataServiceInfo)(nil),
	}
	file_aptos_indexer_v1_grpc_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aptos_indexer_v1_grpc_proto_rawDesc), len(file_aptos_indexer_v1_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_aptos_indexer_v1_grpc_proto_goTypes,
		DependencyIndexes: file_aptos_indexer_v1_grpc_proto_depIdxs,
		MessageInfos:      file_aptos_indexer_v1_grpc_proto_msgTypes,
	}.Build()
	File_aptos_indexer_v1_grpc_proto = out.File
	file_aptos_indexer_v1_grpc_proto_goTypes = nil
	file_aptos_indexer_v1_grpc_proto_depIdxs = nil
}
