// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: aptos/indexer/v1/raw_data.proto

package indexerv1

import (
	v1 "github.com/xiaobaiskill/aptos-grpc-go/aptos/transaction/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is for storage only.
type TransactionsInStorage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required; transactions data.
	Transactions []*v1.Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Required; chain id.
	StartingVersion *uint64 `protobuf:"varint,2,opt,name=starting_version,json=startingVersion,proto3,oneof" json:"starting_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionsInStorage) Reset() {
	*x = TransactionsInStorage{}
	mi := &file_aptos_indexer_v1_raw_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsInStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsInStorage) ProtoMessage() {}

func (x *TransactionsInStorage) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_raw_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsInStorage.ProtoReflect.Descriptor instead.
func (*TransactionsInStorage) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_raw_data_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionsInStorage) GetTransactions() []*v1.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionsInStorage) GetStartingVersion() uint64 {
	if x != nil && x.StartingVersion != nil {
		return *x.StartingVersion
	}
	return 0
}

type GetTransactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required; start version of current stream.
	StartingVersion *uint64 `protobuf:"varint,1,opt,name=starting_version,json=startingVersion,proto3,oneof" json:"starting_version,omitempty"`
	// Optional; number of transactions to return in current stream.
	// If not present, return an infinite stream of transactions.
	TransactionsCount *uint64 `protobuf:"varint,2,opt,name=transactions_count,json=transactionsCount,proto3,oneof" json:"transactions_count,omitempty"`
	// Optional; number of transactions in each `TransactionsResponse` for current stream.
	// If not present, default to 1000. If larger than 1000, request will be rejected.
	BatchSize *uint64 `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3,oneof" json:"batch_size,omitempty"`
	// If provided, only transactions that match the filter will be included.
	TransactionFilter *BooleanTransactionFilter `protobuf:"bytes,4,opt,name=transaction_filter,json=transactionFilter,proto3,oneof" json:"transaction_filter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_aptos_indexer_v1_raw_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_raw_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_raw_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionsRequest) GetStartingVersion() uint64 {
	if x != nil && x.StartingVersion != nil {
		return *x.StartingVersion
	}
	return 0
}

func (x *GetTransactionsRequest) GetTransactionsCount() uint64 {
	if x != nil && x.TransactionsCount != nil {
		return *x.TransactionsCount
	}
	return 0
}

func (x *GetTransactionsRequest) GetBatchSize() uint64 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

func (x *GetTransactionsRequest) GetTransactionFilter() *BooleanTransactionFilter {
	if x != nil {
		return x.TransactionFilter
	}
	return nil
}

type ProcessedRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstVersion  uint64                 `protobuf:"varint,1,opt,name=first_version,json=firstVersion,proto3" json:"first_version,omitempty"`
	LastVersion   uint64                 `protobuf:"varint,2,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedRange) Reset() {
	*x = ProcessedRange{}
	mi := &file_aptos_indexer_v1_raw_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedRange) ProtoMessage() {}

func (x *ProcessedRange) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_raw_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedRange.ProtoReflect.Descriptor instead.
func (*ProcessedRange) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_raw_data_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessedRange) GetFirstVersion() uint64 {
	if x != nil {
		return x.FirstVersion
	}
	return 0
}

func (x *ProcessedRange) GetLastVersion() uint64 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

// TransactionsResponse is a batch of transactions.
type TransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required; transactions data.
	Transactions []*v1.Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Required; chain id.
	ChainId        *uint64         `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	ProcessedRange *ProcessedRange `protobuf:"bytes,3,opt,name=processed_range,json=processedRange,proto3,oneof" json:"processed_range,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionsResponse) Reset() {
	*x = TransactionsResponse{}
	mi := &file_aptos_indexer_v1_raw_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsResponse) ProtoMessage() {}

func (x *TransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_raw_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsResponse.ProtoReflect.Descriptor instead.
func (*TransactionsResponse) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_raw_data_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionsResponse) GetTransactions() []*v1.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionsResponse) GetChainId() uint64 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *TransactionsResponse) GetProcessedRange() *ProcessedRange {
	if x != nil {
		return x.ProcessedRange
	}
	return nil
}

var File_aptos_indexer_v1_raw_data_proto protoreflect.FileDescriptor

const file_aptos_indexer_v1_raw_data_proto_rawDesc = "" +
	"\n" +
	"\x1faptos/indexer/v1/raw_data.proto\x12\x10aptos.indexer.v1\x1a\x1daptos/indexer/v1/filter.proto\x1a&aptos/transaction/v1/transaction.proto\"\xa3\x01\n" +
	"\x15TransactionsInStorage\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.aptos.transaction.v1.TransactionR\ftransactions\x12.\n" +
	"\x10starting_version\x18\x02 \x01(\x04H\x00R\x0fstartingVersion\x88\x01\x01B\x13\n" +
	"\x11_starting_version\"\xda\x02\n" +
	"\x16GetTransactionsRequest\x122\n" +
	"\x10starting_version\x18\x01 \x01(\x04B\x020\x01H\x00R\x0fstartingVersion\x88\x01\x01\x126\n" +
	"\x12transactions_count\x18\x02 \x01(\x04B\x020\x01H\x01R\x11transactionsCount\x88\x01\x01\x12\"\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x04H\x02R\tbatchSize\x88\x01\x01\x12^\n" +
	"\x12transaction_filter\x18\x04 \x01(\v2*.aptos.indexer.v1.BooleanTransactionFilterH\x03R\x11transactionFilter\x88\x01\x01B\x13\n" +
	"\x11_starting_versionB\x15\n" +
	"\x13_transactions_countB\r\n" +
	"\v_batch_sizeB\x15\n" +
	"\x13_transaction_filter\"X\n" +
	"\x0eProcessedRange\x12#\n" +
	"\rfirst_version\x18\x01 \x01(\x04R\ffirstVersion\x12!\n" +
	"\flast_version\x18\x02 \x01(\x04R\vlastVersion\"\xf2\x01\n" +
	"\x14TransactionsResponse\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.aptos.transaction.v1.TransactionR\ftransactions\x12\"\n" +
	"\bchain_id\x18\x02 \x01(\x04B\x020\x01H\x00R\achainId\x88\x01\x01\x12N\n" +
	"\x0fprocessed_range\x18\x03 \x01(\v2 .aptos.indexer.v1.ProcessedRangeH\x01R\x0eprocessedRange\x88\x01\x01B\v\n" +
	"\t_chain_idB\x12\n" +
	"\x10_processed_range2p\n" +
	"\aRawData\x12e\n" +
	"\x0fGetTransactions\x12(.aptos.indexer.v1.GetTransactionsRequest\x1a&.aptos.indexer.v1.TransactionsResponse0\x01BBZ@github.com/xiaobaiskill/aptos-grpc-go/aptos/indexer/v1;indexerv1b\x06proto3"

var (
	file_aptos_indexer_v1_raw_data_proto_rawDescOnce sync.Once
	file_aptos_indexer_v1_raw_data_proto_rawDescData []byte
)

func file_aptos_indexer_v1_raw_data_proto_rawDescGZIP() []byte {
	file_aptos_indexer_v1_raw_data_proto_rawDescOnce.Do(func() {
		file_aptos_indexer_v1_raw_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aptos_indexer_v1_raw_data_proto_rawDesc), len(file_aptos_indexer_v1_raw_data_proto_rawDesc)))
	})
	return file_aptos_indexer_v1_raw_data_proto_rawDescData
}

var file_aptos_indexer_v1_raw_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aptos_indexer_v1_raw_data_proto_goTypes = []any{
	(*TransactionsInStorage)(nil),    // 0: aptos.indexer.v1.TransactionsInStorage
	(*GetTransactionsRequest)(nil),   // 1: aptos.indexer.v1.GetTransactionsRequest
	(*ProcessedRange)(nil),           // 2: aptos.indexer.v1.ProcessedRange
	(*TransactionsResponse)(nil),     // 3: aptos.indexer.v1.TransactionsResponse
	(*v1.Transaction)(nil),           // 4: aptos.transaction.v1.Transaction
	(*BooleanTransactionFilter)(nil), // 5: aptos.indexer.v1.BooleanTransactionFilter
}
var file_aptos_indexer_v1_raw_data_proto_depIdxs = []int32{
	4, // 0: aptos.indexer.v1.TransactionsInStorage.transactions:type_name -> aptos.transaction.v1.Transaction
	5, // 1: aptos.indexer.v1.GetTransactionsRequest.transaction_filter:type_name -> aptos.indexer.v1.BooleanTransactionFilter
	4, // 2: aptos.indexer.v1.TransactionsResponse.transactions:type_name -> aptos.transaction.v1.Transaction
	2, // 3: aptos.indexer.v1.TransactionsResponse.processed_range:type_name -> aptos.indexer.v1.ProcessedRange
	1, // 4: aptos.indexer.v1.RawData.GetTransactions:input_type -> aptos.indexer.v1.GetTransactionsRequest
	3, // 5: aptos.indexer.v1.RawData.GetTransactions:output_type -> aptos.indexer.v1.TransactionsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aptos_indexer_v1_raw_data_proto_init() }
func file_aptos_indexer_v1_raw_data_proto_init() {
	if File_aptos_indexer_v1_raw_data_proto != nil {
		return
	}
	file_aptos_indexer_v1_filter_proto_init()
	file_aptos_indexer_v1_raw_data_proto_msgTypes[0].OneofWrappers = []any{}
	file_aptos_indexer_v1_raw_data_proto_msgTypes[1].OneofWrappers = []any{}
	file_aptos_indexer_v1_raw_data_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aptos_indexer_v1_raw_data_proto_rawDesc), len(file_aptos_indexer_v1_raw_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aptos_indexer_v1_raw_data_proto_goTypes,
		DependencyIndexes: file_aptos_indexer_v1_raw_data_proto_depIdxs,
		MessageInfos:      file_aptos_indexer_v1_raw_data_proto_msgTypes,
	}.Build()
	File_aptos_indexer_v1_raw_data_proto = out.File
	file_aptos_indexer_v1_raw_data_proto_goTypes = nil
	file_aptos_indexer_v1_raw_data_proto_depIdxs = nil
}
